param(
    [string]$Target = ".",
    [switch]$Force,
    [switch]$SkipDetection
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$TargetPath = (Resolve-Path $Target).Path
$Version = (Get-Content (Join-Path $RepoRoot "VERSION") -Raw).Trim()

Write-Host ""
Write-Host "======================================="
Write-Host " AgentSpec v$Version - Project Init"
Write-Host "======================================="
Write-Host "Target: $TargetPath"
Write-Host ""

if (-not $SkipDetection) {
    $detectScript = Join-Path $ScriptDir "detect-project.ps1"
    $detection = & powershell -NoProfile -ExecutionPolicy Bypass -File $detectScript -Target $TargetPath | ConvertFrom-Json

    Write-Host "Detected project stack:"
    foreach ($category in $detection.detected.psobject.Properties) {
        $values = @($category.Value)
        if ($values.Count -gt 0) {
            Write-Host ("  {0}: {1}" -f $category.Name, ($values -join ", "))
        }
    }
    Write-Host ""
}

$items = @(
    "AGENTS.md",
    "CLAUDE.md",
    "VERSION"
)

foreach ($item in $items) {
    $source = Join-Path $RepoRoot $item
    $destination = Join-Path $TargetPath $item

    if ((Test-Path $destination) -and -not $Force) {
        Write-Host "SKIP: $item already exists"
        continue
    }

    Copy-Item -Path $source -Destination $destination -Force
    Write-Host "COPY: $item"
}

$agentsSource = Join-Path $RepoRoot ".agents"
$agentsDestination = Join-Path $TargetPath ".agents"

if (-not (Test-Path $agentsDestination)) {
    New-Item -ItemType Directory -Path $agentsDestination | Out-Null
}

foreach ($directory in @("core", "skills", "workflows", "checklists", "templates")) {
    $source = Join-Path $agentsSource $directory
    $destination = Join-Path $agentsDestination $directory
    if ((Test-Path $destination) -and $Force) {
        Copy-Item -Path $source -Destination $agentsDestination -Recurse -Force
    } elseif (-not (Test-Path $destination)) {
        Copy-Item -Path $source -Destination $agentsDestination -Recurse
    }
}

$manifestSource = Join-Path $agentsSource "manifest.md"
$manifestDestination = Join-Path $agentsDestination "manifest.md"
if ((Test-Path $manifestDestination) -and -not $Force) {
    Write-Host "SKIP: .agents/manifest.md already exists"
} else {
    Copy-Item $manifestSource $manifestDestination -Force
    Write-Host "COPY: .agents/manifest.md"
}

$contextPath = Join-Path $agentsDestination "context"
if (-not (Test-Path $contextPath)) {
    New-Item -ItemType Directory -Path $contextPath | Out-Null
}

$templateNames = @(
    "project.md",
    "architecture.md",
    "database.md",
    "design-system.md",
    "permissions.md",
    "features.md"
)

foreach ($name in $templateNames) {
    $source = Join-Path $agentsSource "templates\$name"
    $destination = Join-Path $contextPath $name

    if ((Test-Path $destination) -and -not $Force) {
        Write-Host "SKIP: .agents/context/$name already exists"
        continue
    }

    Copy-Item -Path $source -Destination $destination -Force
    Write-Host "COPY: .agents/context/$name"
}

# Record detected stack without exposing environment variables or secrets.
if (-not $SkipDetection) {
    $detectionPath = Join-Path $contextPath "detected-stack.md"
    $lines = @(
        "# Detected Project Stack",
        "",
        "Generated by AgentSpec v$Version.",
        "This file contains structural detection only. It does not read or copy environment secrets.",
        ""
    )

    foreach ($category in $detection.detected.psobject.Properties) {
        $values = @($category.Value)
        if ($values.Count -gt 0) {
            $lines += "## $($category.Name)"
            foreach ($value in $values) { $lines += "- $value" }
            $lines += ""
        }
    }

    if ((Test-Path $detectionPath) -and -not $Force) {
        Write-Host "SKIP: .agents/context/detected-stack.md already exists"
    } else {
        Set-Content -Path $detectionPath -Value $lines -Encoding UTF8
        Write-Host "CREATE: .agents/context/detected-stack.md"
    }
}

Write-Host ""
Write-Host "AgentSpec v$Version initialized successfully."
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Review .agents/context/"
Write-Host "2. Replace placeholders with project-specific facts."
Write-Host "3. Ask your coding agent to inspect the repository and improve the context files."
Write-Host "4. Do not place secrets in AgentSpec context files."
Write-Host ""
